function valid = is_valid(param)
valid = isreal(param) && all(isfinite(param)) && ...
    (param(1) > 0 && param(1) <= 0.1) && ...
    (param(2) >= 0.6 && param(2) <= 0.99) && ...
    (param(3) > 0 && param(3) <= 0.3) && ...
    (param(2) + param(3) <= 0.99);
end